image: node:latest
stages:
  - install
  - test
  - build
install:
  stage: install
  script: npm install
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

vitest:
  stage: test
  dependencies:
    - install
  script:
    - npm run test

build:
  stage: build
  dependencies:
    - install
  script:
    - docker build
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - dist/

